name = input("What is your name? ")
print("Hello " + name + "!")
input("How are you today? ")
print("I see, " + name)
print("I myself am a little nervous, because I am meeting so many new people.")
input("What do you like to do for fun, " + name + "?")
print("That sounds interesting")
print("I'd like to know some more about you.")
color = input("What is your favorite color? ")
print("It's funny you should say that! I just got a new " + color + " keyboard the other day.")
input("Will you be my friend? ")
print("OK")
